camunda.operate:
  # Set operate username and password.
  # If user with <username> does not exists it will be created.
  # Default: demo/demo
  #username:
  #password:
  # ELS instance to store Operate data
  elasticsearch:
    # Cluster name
    clusterName: elasticsearch
    # URL
    url: http://elasticsearch:9200
  # Zeebe instance
  zeebe:
    # Gateway address
    gatewayAddress: zeebe:26500
  # ELS instance to export Zeebe data to
  zeebeElasticsearch:
    # Cluster name
    clusterName: elasticsearch
    # URL
    url: http://elasticsearch:9200
    # Index prefix, configured in Zeebe Elasticsearch exporter
    prefix: zeebe-record-dev